---
# vars file for atom

_atom_requirements:
  apt:
    - apt-transport-https

atom_requirements: "{{ _atom_requirements[ansible_pkg_mgr] | default(omit) }}"

_atom_package:
  apt:
    url: 'https://github.com/atom/atom/releases/download/v1.63.1/atom-amd64.deb'
    name: atom-amd64.deb
  dnf: &rpmpackage
    url: 'https://atom.io/download/rpm'
    name: atom.x86_64.rpm
  yum: *rpmpackage
  zypper: *rpmpackage

atom_package_url: '{{ _atom_package[ansible_pkg_mgr]["url"] }}'
atom_package: "{{ _atom_package[ansible_pkg_mgr]['name'] }}"
